# Generated by Django 4.0.5 on 2022-06-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_customer_order_store_item_digital_store_item_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_Images',
            new_name='Store_Image',
        ),
        migrations.AlterModelOptions(
            name='shipping_address',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
