# Generated by Django 4.0.5 on 2022-06-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_rename_store_images_store_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_item',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='store_image',
            options={'verbose_name_plural': 'Store Items'},
        ),
        migrations.AlterModelOptions(
            name='store_item',
            options={'verbose_name_plural': 'Store Items'},
        ),
    ]
